version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: build/Dockerfile
    container_name: backend
    env_file:
      - ./backend/.env
    environment:
      - INPUT_FILE=/app/input.txt
      - SERVER_PORT=${SERVER_PORT:-8080}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    ports:
      - "${SERVER_PORT:-8080}:8080"
    networks:
      - gosolve_network

  frontend:
    build:
      context: ./frontend
      dockerfile: build/Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8080
    networks:
      - gosolve_network

networks:
  gosolve_network:
    driver: bridge
